name: Linux Native CLI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    name: Builds Linux Native CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0
      - name: Install GraalVM
        env:
          GRAAL_VERSION: 21.3.0
          GRAAL_OS: linux-amd64
        run: ./install-graal.sh
      - name: Install Native Image
        run: ./graalvm/bin/gu install native-image
      - name: Build the JAR
        env:
          JAVA_HOME: ./graalvm
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        run: ./gradlew micronaut-cli:shadowJar --no-daemon
      - name: Build Native Image
        run: ./graalvm/bin/native-image --no-fallback -cp starter-cli/build/libs/micronaut-cli-*-all.jar
      - name: Verify Build
        run: ./mn --version
      - name: Verify Create App
        run: ./mn create-app test
      - name: Package Build
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          mkdir -p mn-linux-amd64-snapshot/bin
          mv ./mn mn-linux-amd64-snapshot/bin
          cp ./LICENSE mn-linux-amd64-snapshot/
          zip -r mn-linux-amd64-snapshot.zip ./mn-linux-amd64-snapshot
      - name: Upload Snapshot
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/2.2.x'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: mn-linux-amd64-snapshot
          path: mn-linux-amd64-snapshot.zip
