name: Release Notes
on:
  pull_request:
    types: [closed]
    branches:
      - master
  issues:
    types: [closed,reopened]
  push:
    branches:
      - master
    paths:
      - ".github/workflows/release-notes.yml"
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: micronaut-projects/github-actions/release-notes@master
        id: release_notes
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: master
          draft: true
          name: Micronaut Launch ${{ steps.release_notes.outputs.next_version }}
          tag: v${{ steps.release_notes.outputs.next_version }}
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GH_TOKEN }}